name = "audit"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Audit"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[require]]
name = "aeneas"
git = { url = "https://github.com/AeneasVerif/aeneas.git", subDir = "backends/lean" }
rev = "d71d2e3f2cb763f7faf15ab606ac9cf32da8dead"

[[lean_lib]]
name = "Audit"
