//! Emits `OUT_DIR/journal_layout.rs`: `JOURNAL_CAP_SLOTS` and `JOURNAL_READ_CHUNK_BYTES`.
//!
//! Optional env vars (compile time):
//! - **`JOURNAL_CAP_SLOTS`** — journal slot capacity (default **`4096`**; any **`usize >= 1`**).
//! - **`JOURNAL_READ_CHUNK_MAX`** — hard upper bound on chunk / stack buffer (default **`32768`**).
//! - **`JOURNAL_READ_CHUNK_TARGET`** — **preferred** upper bound on chunk (default **`5120`**). The
//!   build picks the **largest** valid chunk **under this cap first**; it must be at least **`5`**.
//!
//! **Selection rule:** let **`R = JOURNAL_CAP_SLOTS * 5`**. `JOURNAL_READ_CHUNK_BYTES` is the **largest**
//! **`d`** such that **`d % 5 == 0`**, **`R % d == 0`**, and **`d <= floor5(min(R, JOURNAL_READ_CHUNK_TARGET, JOURNAL_READ_CHUNK_MAX))`**
//! (`floor5` rounds down to a multiple of **`5`**). For valid inputs there is always a solution (**`d = 5`** works).
//!
//! Rationale: `init` always performs at least one full `Memory::read` of size **`JOURNAL_READ_CHUNK_BYTES`**
//! before it can know the journal is empty. Capping the **preferred** chunk near the historical
//! **`5120`** avoids **read amplification** on checkpointed (empty-tail) reopen paths, while still
//! allowing a larger **`JOURNAL_READ_CHUNK_MAX`** override when you intentionally want fewer, bigger reads.

/// Default preferred replay read size (`Memory::read` / `[u8; N]` in `bitmap::RoaringBitmap::init`).
/// Picked to match historical behavior when it divides **`JOURNAL_CAP_SLOTS * 5`**.
const DEFAULT_CHUNK_TARGET: usize = 5120;

/// Absolute upper bound on `JOURNAL_READ_CHUNK_BYTES` (Wasm stack `[u8; N]`).
const DEFAULT_CHUNK_HARD_MAX: usize = 32 * 1024;

#[inline]
fn floor_multiple_of_five(n: usize) -> usize {
    (n / 5) * 5
}

/// Largest **`chunk`** with **`chunk % 5 == 0`**, **`region % chunk == 0`**, **`5 <= chunk <= floor5(min(cap, region))`**.
fn greatest_valid_chunk_bounded(region: usize, cap: usize) -> Option<usize> {
    assert_eq!(region % 5, 0);
    assert!(region >= 5);

    let cap = floor_multiple_of_five(cap.min(region));
    if cap < 5 {
        return None;
    }

    let mut chunk = cap;
    loop {
        if region.is_multiple_of(chunk) {
            return Some(chunk);
        }
        if chunk < 5 {
            return None;
        }
        chunk -= 5;
    }
}

fn choose_journal_read_chunk(region: usize, target: usize, hard_max: usize) -> usize {
    assert!(
        hard_max >= 5,
        "JOURNAL_READ_CHUNK_MAX ({hard_max}) must be >= 5 (journal record size)"
    );

    let target_cap = floor_multiple_of_five(target.min(hard_max).min(region));
    assert!(
        target_cap >= 5,
        "JOURNAL_READ_CHUNK_TARGET ({target}) is too small after rounding; need at least one 5-byte journal record"
    );

    greatest_valid_chunk_bounded(region, target_cap).unwrap_or_else(|| {
        panic!("internal error: chunk=5 should divide region={region}; target_cap={target_cap}")
    })
}

fn main() {
    let out_dir = std::env::var_os("OUT_DIR").expect("OUT_DIR must be set by Cargo");

    let slots_str = std::env::var("JOURNAL_CAP_SLOTS").unwrap_or_else(|_| "4096".to_string());
    let slots: usize = slots_str.parse().unwrap_or_else(|err| {
        panic!("JOURNAL_CAP_SLOTS={slots_str:?} is not a valid usize: {err}");
    });
    assert!(slots > 0, "JOURNAL_CAP_SLOTS must be > 0");

    let max_chunk_str = std::env::var("JOURNAL_READ_CHUNK_MAX")
        .unwrap_or_else(|_| DEFAULT_CHUNK_HARD_MAX.to_string());
    let max_chunk: usize = max_chunk_str.parse().unwrap_or_else(|err| {
        panic!("JOURNAL_READ_CHUNK_MAX={max_chunk_str:?} is not a valid usize: {err}")
    });
    assert!(
        max_chunk >= 5,
        "JOURNAL_READ_CHUNK_MAX ({max_chunk}) must be >= 5 (journal record size)"
    );

    let chunk_target_str = std::env::var("JOURNAL_READ_CHUNK_TARGET")
        .unwrap_or_else(|_| DEFAULT_CHUNK_TARGET.to_string());
    let chunk_target: usize = chunk_target_str.parse().unwrap_or_else(|err| {
        panic!("JOURNAL_READ_CHUNK_TARGET={chunk_target_str:?} is not a valid usize: {err}")
    });
    assert!(
        chunk_target >= 5,
        "JOURNAL_READ_CHUNK_TARGET ({chunk_target}) must be >= 5"
    );

    let region = slots
        .checked_mul(5)
        .expect("JOURNAL_CAP_SLOTS * 5 must fit in usize");
    assert!(
        region >= 5,
        "journal region ({region} bytes): internal invariant violated (need >= one record)"
    );

    let read_chunk = choose_journal_read_chunk(region, chunk_target, max_chunk);

    let path = std::path::Path::new(&out_dir).join("journal_layout.rs");
    std::fs::write(
        &path,
        format!(
            "// Generated by build.rs (`JOURNAL_CAP_SLOTS`, `JOURNAL_READ_CHUNK_*`).\n\
             \n\
             /// Journal slot capacity set at crate build time; must match header offset `12` (`u64`) on disk.\n\
             pub const JOURNAL_CAP_SLOTS: usize = {slots};\n\
             \n\
             /// Replay read granularity: greatest divisor of `JOURNAL_CAP_SLOTS * 5` under `JOURNAL_READ_CHUNK_TARGET`,\n\
             /// capped by `JOURNAL_READ_CHUNK_MAX` (multiples of `5` only).\n\
             pub const JOURNAL_READ_CHUNK_BYTES: usize = {read_chunk};\n"
        ),
    )
    .unwrap_or_else(|e| panic!("write {}: {e}", path.display()));

    println!("cargo:rerun-if-env-changed=JOURNAL_CAP_SLOTS");
    println!("cargo:rerun-if-env-changed=JOURNAL_READ_CHUNK_MAX");
    println!("cargo:rerun-if-env-changed=JOURNAL_READ_CHUNK_TARGET");
}
